# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b20453ca4c61b00df11d68fa4462094a06aad68c49df74996aedb2f5765ef0c2f3293faa9bcd30910fbc1675241fca64540dda6e9022f53abe622250e2d4c76

test:
  secret_key_base: 634a03256d5dd3a9c7908e2eb65bc42fa87a1fed84766d518327084e561f636f6aadafe2c656a837beabb6ac0d399d89bdae97054981c25b5ad0d5b84f846cf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
